# Generated by Django 4.2.11 on 2026-03-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='ubicacion',
            field=models.CharField(max_length=100),
        ),
    ]
