# Generated by Django 4.2.11 on 2026-03-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_alter_reporte_descripcion_alter_reporte_titulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='reporte',
            name='aula_detalle',
            field=models.CharField(default='sin especificar', help_text='Ej: Aula 5, Baño de hombres, Pasillo', max_length=100, verbose_name='Aula o lugar específico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='edificio',
            field=models.CharField(choices=[('Edificio A', 'Edificio A'), ('Edificio B', 'Edificio B'), ('Edificio K', 'Edificio K (Sistemas)'), ('Edificio L', 'Edificio L'), ('Laboratorios', 'Laboratorios Pesados'), ('Cafetería', 'Cafetería'), ('Centro de Cómputo', 'Centro de Cómputo'), ('Otro', 'Otro / Áreas Comunes')], default='Edificio K', max_length=50),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título del fallo'),
        ),
    ]
