# Generated by Django 4.2.11 on 2026-03-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_remove_reporte_ubicacion_reporte_aula_detalle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='aula_detalle',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='edificio',
        ),
        migrations.AddField(
            model_name='reporte',
            name='lugar_especifico',
            field=models.CharField(default='sin especificaciones', max_length=200, verbose_name='¿Dónde es?'),
            preserve_default=False,
        ),
    ]
