# Generated by Django 6.0.3 on 2026-03-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_remove_reporte_aula_detalle_remove_reporte_edificio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='usuario',
        ),
        migrations.AddField(
            model_name='reporte',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('RESUELTO', 'Resuelto')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='lugar_especifico',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
