# Generated by Django 4.2.11 on 2026-03-27 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportes', '0005_remove_reporte_usuario_reporte_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mis_reportes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reporte',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESO', 'En proceso'), ('RESUELTO', 'Resuelto')], default='PENDIENTE', max_length=20),
        ),
    ]
